local old_ui_pda_taskboard_tab_trigger_generate_available_tasks = ui_pda_taskboard_tab.trigger_generate_available_tasks
function ui_pda_taskboard_tab.trigger_generate_available_tasks(npc_list)
    if not IsWarfare() then
        old_ui_pda_taskboard_tab_trigger_generate_available_tasks(npc_list)
        return
    end

    local npc_list_sim_traders = {} -- contains traders, barmans, medics, mechanics
    local npc_list_others = {}
    for _,npc in pairs(npc_list) do
        if warfare.is_warfare_trader(npc) then
            npc_list_sim_traders[#npc_list_sim_traders + 1] = npc
        else
            npc_list_others[#npc_list_others + 1] = npc
        end
    end

    old_ui_pda_taskboard_tab_trigger_generate_available_tasks(npc_list_others)

    for _,npc in pairs(npc_list_sim_traders) do
        ui_pda_taskboard_tab.currently_processed_npc_id = npc:id()
        axr_task_manager.generate_available_tasks(npc, false)
        ui_pda_taskboard_tab.currently_processed_npc_id = nil
    end
end