function add_time(time, secs)
    local Y, M, D, h, m, s, ms = 0, 0, 0, 0, 0, 0, 0
	Y, M, D, h, m, s, ms = time:get(Y, M, D, h, m, s, ms)
	s = s + secs
	m = m + math.floor(s / 60)
	s = s % 60
	h = h + math.floor(m / 60)
	m = m % 60
	D = D + math.floor(h / 24)
	h = h % 24

	local days_in_month = {31, 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31}
	if Y % 4 == 0 and (Y % 100 ~= 0 or Y % 400 == 0) then
		days_in_month[2] = 29
	end

	while D > days_in_month[M] do
		D = D - days_in_month[M]
		M = M + 1
		if M > 12 then
			M = 1
			Y = Y + 1
			if Y % 4 == 0 and (Y % 100 ~= 0 or Y % 400 == 0) then
				days_in_month[2] = 29
			else
				days_in_month[2] = 28
			end
		end
	end

    local res = game.get_game_time()
	res:set(Y, M, D, h, m, s, ms)

	return res
end