local old_guards_spawner_on_game_start = guards_spawner.on_game_start
guards_spawner.on_game_start = function()
	if _G.WARFARE then
		guards_spawner.upd_upd_tmr = 60000
		if guards_spawner.guards_t["mar_smart_terrain_8_11"] then
			guards_spawner.guards_t["mar_smart_terrain_8_11"].max_amount = 3
		end

		-- military base middle
		guards_spawner.guards_t["agr_smart_terrain_1_6"] = { factions = { "army" }, max_amount = 1, ranks = { "advanced", "veteran" }, smart_faction = "army", squads = {} }
		-- military base northerth half
		guards_spawner.guards_t["agr_smart_terrain_1_6_near_1"] = { factions = { "army" }, max_amount = 1, ranks = { "novice", "advanced" }, smart_faction = "army", squads = {} }
		-- military base southern half
		guards_spawner.guards_t["agr_smart_terrain_1_6_near_2"] = { factions = { "army" }, max_amount = 1, ranks = { "novice", "advanced" }, smart_faction = "army", squads = {} }

		-- bandit base north
		guards_spawner.guards_t["val_smart_terrain_7_3"] = { factions = { "bandit" }, max_amount = 1, ranks = { "novice", "advanced" }, smart_faction = "bandit", squads = {} }

		if guards_spawner.guards_t["mil_smart_terrain_2_4"] then
			guards_spawner.guards_t["mil_smart_terrain_2_4"].max_amount = 3
		end

		-- freedom base north (entrance)
		guards_spawner.guards_t["mil_smart_terrain_7_8"] = { factions = { "freedom" }, max_amount = 1, ranks = { "novice", "advanced" }, smart_faction = "freedom", squads = {} }
		-- freedom base west
		guards_spawner.guards_t["mil_smart_terrain_7_10"] = { factions = { "freedom" }, max_amount = 1, ranks = { "novice", "advanced" }, smart_faction = "freedom", squads = {} }

		if guards_spawner.guards_t["pri_monolith"] then
			guards_spawner.guards_t["pri_monolith"].max_amount = 2
		end
	end
	old_guards_spawner_on_game_start()
end

local old_guards_spawner_get_random_faction = guards_spawner.get_random_faction
guards_spawner.get_random_faction = function(smart, guard)
	if _G.WARFARE and smart.owning_faction and smart.owning_faction ~= "none" and warfare_options.options.factions[smart.owning_faction].participate_in_warfare then
		return smart.owning_faction
	end

	return old_guards_spawner_get_random_faction(smart, guard)
end