local old_smr_pop_smart_can_respawn = smr_pop.smart_can_respawn
smr_pop.smart_can_respawn = function(smart)
    if _G.WARFARE then
        smr_debug.get_log().info("warfare", "warfare detected, skipping smr_pop.smart_can_respawn")
        smr_pop.curr_time = game.get_game_time()
    end
    return old_smr_pop_smart_can_respawn(smart)
end

local old_smr_pop_adjust_squad_size = smr_pop.adjust_squad_size
smr_pop.adjust_squad_size = function(smart, squad)
    if _G.WARFARE then
        smr_debug.get_log().info("warfare", "warfare detected, skipping smr_pop.adjust_squad_size")
        return
    end
    return old_smr_pop_adjust_squad_size(smart, squad)
end
