local old_smr_pop_smart_can_respawn = smr_pop.smart_can_respawn
smr_pop.smart_can_respawn = function(smart)
    if _G.WARFARE then
        printf("WARFARE mode active - smr_pop.smart_can_respawn triggered")
    end
    return old_smr_pop_smart_can_respawn(smart)
end

--adjust_squad_size
local old_smr_pop_adjust_squad_size = smr_pop.adjust_squad_size
smr_pop.adjust_squad_size = function(smart, squad)
    if _G.WARFARE then
        return
    end

    old_smr_pop_adjust_squad_size(smart, squad)
end